driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  sudo: true
  reporter:
    - cli
    - json:./results/<%= Time.now.utc.strftime('%Y%m%d%H%M%S') %>-%{platform}_%{suite}.json
  inspec_tests:
    - path: ./
  input_files:
    - inspec.yml

platforms:
- name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[os-hardening::default]