driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  sudo: true
  reporter:
    - cli
    - json:results.json
  inspec_tests:
    - path: ./

platforms:
- name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[os-hardening::default]
