control "V-75817" do
  title "The Ubuntu operating system must record time stamps for audit records
that can be mapped to Coordinated Universal Time (UTC) or Greenwich Mean Time
(GMT)."
  desc  "If time stamps are not consistently applied and there is no common
time reference, it is difficult to perform forensic analysis.

    Time stamps generated by the Ubuntu operating system include date and time.
Time is commonly expressed in Coordinated Universal Time (UTC), a modern
continuation of Greenwich Mean Time (GMT), or local time with an offset from
UTC.
  "
  impact 0.5
  tag "gtitle": "SRG-OS-000359-GPOS-00146"
  tag "gid": "V-75817"
  tag "rid": "SV-90497r2_rule"
  tag "stig_id": "UBTU-16-030120"
  tag "fix_id": "F-82447r1_fix"
  tag "cci": ["CCI-001890"]
  tag "nist": ["AU-8 b", "Rev_4"]
  tag "false_negatives": nil
  tag "false_positives": nil
  tag "documentable": false
  tag "mitigations": nil
  tag "severity_override_guidance": false
  tag "potential_impacts": nil
  tag "third_party_tools": nil
  tag "mitigation_controls": nil
  tag "responsibility": nil
  tag "ia_controls": nil
  tag "check": "The time zone must be configured to use Coordinated Universal
Time (UTC) or Greenwich Mean Time (GMT). To verify run the following command.

# sudo timedatectl status | grep -i \"time zone\"
Time zone: UTC (UTC, +0000)

If \"Time zone\" is not set to UTC or GMT, this is a finding."
  tag "fix": "To configure the system time zone to use Coordinated Universal
Time (UTC) or Greenwich Mean Time (GMT), run the following command replacing
[ZONE] with UTC or GMT.

# sudo timedatectl set-timezone [ZONE]"
end

